# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "workstation" => {"memory" => "1024", "cpu" => "2", "ip" => "20", "image" => "ubuntu/bionic64", "vnic" => "vbox0"},
  "frontend" => {"memory" => "1024", "cpu" => "2", "ip" => "30", "image" => "debian/buster64", "vnic" => "vbox1"},
  "middleware" => {"memory" => "1024", "cpu" => "2", "ip" => "40", "image" => "ubuntu/bionic64", "vnic" => "vbox1"},
  "backend" => {"memory" => "1024", "cpu" => "2", "ip" => "50", "image" => "centos/7", "vnic" => "vbox1"}
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.exemplo.com.br"
      machine.vm.network "private_network", ip: "172.16.100.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/x52-Linux-Servers"]
        if name == "backend" and not File.file?('NewVirtualDisk1.vdi')
          vb.customize ['createhd', '--filename', 'NewVirtualDisk1.vdi', '--size', 20 * 1024]
          vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata']
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'NewVirtualDisk1.vdi']
        end
      end
        if "#{conf["image"]}" == "ubuntu/bionic64"
          machine.vm.provision "shell", inline: "apt install python -y"
        end
    end
  end
  config.vm.provision "shell", path: "env.sh"
end
