# -*- mode: ruby -*-
# vi: set ft=ruby  :

####    WORKSTATION
####    backend.domain.com.br

# Informações
# autor: "w.luis.araujo"
# email: w.luis.araujo@gmail.com
#
# OBS.: Execute os comandos a seguir para instalar os plugins
# vagrant plugin install vagrant-disksize
# vagrant plugin install vagrant-vbguest
#
# Inicie as VMs com os seguintes comandos
# vagrant init
# vagrant up --provision
#
# Para acessar cada VM via SSH
# vagrant ssh backend
#
# Para desligar as VMs
# vagrant halt
#
# Para remover as VMs
# vagrant destroy
#

# Verificando e instalando as dependências de plugins do Vagrant
required_plugins = %w( vagrant-disksize vagrant-vbguest )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
  raise "The plugin #{plugin} is required. Please run `vagrant plugin install #{plugin}`"  unless Vagrant.has_plugin? plugin
end

#------------------------------------------------#
# Declaração de variáveis
#------------------------------------------------#
Vagrant.require_version ">= 2.0.0"
VAGRANTFILE_API_VERSION = "2"
TIMEOUT = 600

# Nome da box (template do S.O) obtido em:
#  https://app.vagrantup.com/boxes/search
BOXNAME     = "centos/7"

# Endereço da rede das máquinas virtuais
NET_ADDRESS = "172.16.100"

# Tamanho do HD da VM
DISKSIZE = "20GB"

# Diretório de origem do seu host.
# Pode ser um diretório com path (caminho) relativo no qual está o arquivo Vagranfile
# ou pode ser um path (caminho) completo.
#
# O conteúdo das pastas será sincronizado após a execução de um dos comandos a seguir
# --> vagrant up
# --> vagrant reload
# ./x52_linux_servers/files/
DIR_SOURCE = "../../files/"

# Diretório destino dentro da VM
DIR_DESTINY = "/templates/"

# Definindo o locale da VM, independente do host hospedeiro
ENV["LC_ALL"] = "en_US.UTF-8"
#------------------------------------------------#


#*******************************#
# Início das configurações das VMs
#*******************************#

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  #---------------------------------------
  # Criando a VM backend
  config.vm.define :backend, primary: true do |backend_config|
    backend_config.vm.provider "virtualbox" do |vb|
        vb.memory = '1024'
        vb.cpus   = '1'
        vb.name   = 'backend.exemplo.com.br'
        vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
        vb.customize [ "modifyvm", :id, "--hostonlyadapter1", "vboxnet1"]
        vb.customize [ "modifyvm", :id, "--groups", "/x52-Linux-Servers"]
    end
    backend_config.vm.hostname         = 'backend.exemplo.com.br'
    backend_config.vm.box              = BOXNAME
    backend_config.vm.boot_timeout     = TIMEOUT
    backend_config.vm.box_check_update = true
    backend_config.vm.network "private_network", ip: "#{NET_ADDRESS}.102"
    backend_config.vm.synced_folder DIR_SOURCE, DIR_DESTINY
    end
  end